### ISSUE TITLE
How to tail remote log file?

### ISSUE THREAD

**Issue by reddysainathn** [pschweitz/insidelog#1]
How do I setup ssh to tail a remote log file?

**Comment by pschweitz** [comment]
Hi,

There are several ways of configuration.

Please refer to the page 6 of the user manual for SSH:
https://github.com/pschweitz/insidelog/blob/master/UserManual.pdf

Otherwise to tail remote files located on a Windows server I recommend to open a read only shared drive, then to tail them like local files.

Thanks for using in'side log

**Comment by reddysainathn** [comment]
Is this the right way of ssh string at right place? I tried multiple ways, did not go thru. Can you help me with this....

`ssh://<userName>@<hostname>:/<path>`

![image](https://user-images.githubusercontent.com/10643404/50651010-0eb42c80-0f50-11e9-9268-83c97e25ed33.png)

**Comment by pschweitz** [comment]
Yes it is like the connection string you provided. 

Please make sure the server is running an ssh server (sshd), and accepting login with the user you want to (root is not authorized by default on many distributions).

Finally check on the server side, the log files of the ssh server to identify a potential issue.
Thanks.

**Comment by reddysainathn** [comment]
This Helped me. Thank you.
